### ISSUE TITLE
How to properly configure with Prettier and VSCode

### ISSUE THREAD

**Issue by meiuwa** [ota-meshi/stylelint-plugin-stylus#35]
Noob question, how do I properly make it work with [Prettier](https://prettier.io/) and VSCode? I tried to use this but I'm getting an error:

![Screenshot_20210127_181425](https://user-images.githubusercontent.com/44991669/105977415-4f99b380-60cc-11eb-8d02-d80c4bfd0664.png)

Steps to reproduce:

- Install [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) and [Stylelint](https://marketplace.visualstudio.com/items?itemName=stylelint.vscode-stylelint) VSCode extensions
- Install packages:

```console
npm i -D postcss postcss-styl postcss-syntax prettier stylelint stylelint-plugin-stylus stylelint-prettier
```

- Configure VSCode workspace:

```json
{
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
        "source.fixAll": true
    },
    "stylelint.customSyntax": "stylelint-plugin-stylus/custom-syntax",
    "stylelint.validate": [
        "css",
        "html",
        "javascript",
        "javascriptreact",
        "less",
        "markdown",
        "postcss",
        "sass",
        "scss",
        "source.css.styled",
        "source.markdown.math",
        "styled-css",
        "sugarss",
        "svelte",
        "typescript",
        "typescriptreact",
        "vue",
        "vue-html",
        "vue-postcss",
        "xml",
        "xsl",
        "stylus"
    ]
}
```

- Configure Prettier:

```json
{
    "tabWidth": 4,
    "useTabs": false,
    "semi": true,
    "singleQuote": false,
    "jsxSingleQuote": false,
    "jsxBracketSameLine": false,
    "trailingComma": "none",
    "bracketSpacing": true,
    "arrowParens": "always",
    "proseWrap": "never",
    "endOfLine": "lf",
    "embeddedLanguageFormatting": "off"
}
```

- Configure Stylelint:

```json
{
    "customSyntax": "stylelint-plugin-stylus/custom-syntax",
    "syntax": [
        "stylus"
    ],
    "plugins": [
        "stylelint-prettier",
        "stylelint-plugin-stylus"
    ],
    "rules": {
        "prettier/prettier": true
    }
}
```

- Lastly, try linting `.styl` file.

What am I missing here? Can someone guide me :disappointed:

**Comment by ota-meshi** [comment]
As far as I know, Prettier does not support stylus. I think you need to exclude Prettier from your configuration.

https://github.com/prettier/prettier/issues/2465

**Comment by meiuwa** [comment]
@ota-meshi Got it. I'll close this issue.
